pipeline {
    agent any
    tools {
        maven 'LocalMaven'
    }
    stages {
        stage('Initialize') {
            steps {
                cleanWs() // Deletes everything before the build starts
            }
        }
        stage('Checkout') {
            steps {
                git url: 'https://github.com/moiseiyaba7-tech/Advanced-OOP-Assignments.git', 
                    branch: 'main', 
                    credentialsId: 'github-token'
            }
        }
        stage('Build & Test') {
            steps {
                dir('GridLayouts') {
                    // -Drelease=17 fixes the "system modules" warning from your logs
                    bat 'mvn clean compile test -Dmaven.compiler.release=17 -Dmaven.compiler.useIncrementalCompilation=false'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube') {
            steps {
                dir('GridLayouts') {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn sonar:sonar -Dsonar.token=squ_69fa4e871dcce8695e6f0f23cfa4396e3b8b57e5'
                    }
                }
            }
        }
    }
}