pipeline {
    agent any
    tools { maven 'LocalMaven' }
    stages {
        stage('Initialize') {
            steps {
                deleteDir() // Physically wipes the workspace folder
            }
        }
        stage('Checkout') {
            steps {
                git url: 'https://github.com/moiseiyaba7-tech/Advanced-OOP-Assignments.git', 
                    branch: 'main', 
                    credentialsId: 'github-token'
            }
        }
        stage('Build & Test') {
            steps {
                dir('GridLayouts') {
                    // Aggressive clean and forced re-compilation
                    bat 'mvn clean compile test -Dmaven.compiler.useIncrementalCompilation=false'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube') {
            steps {
                dir('GridLayouts') {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn sonar:sonar -Dsonar.token=squ_69fa4e871dcce8695e6f0f23cfa4396e3b8b57e5'
                    }
                }
            }
        }
    }
}